version: "3.9"

services:
    pgsql:
        image: mysql:8
        restart: unless-stopped
        container_name: "${DB_CONTAINER_NAME:-pgsql}"
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_DATABASE: "${DB_DATABASE}"
        networks:
            - local
        ports:
            - ${DB_PORT:-3306}:3306
        volumes:
            - db_data:/var/lib/mysql:z
    minio:
        image: quay.io/minio/minio:RELEASE.2023-05-18T00-05-36Z
        command: server /data --console-address ":9001"
        restart: unless-stopped
        ports:
            - 9001:9001
            - 9000:9000
        environment:
            MINIO_ROOT_USER: minio
            MINIO_ROOT_PASSWORD: asdfasdf
        healthcheck:
            test: "curl -f http://localhost:9000/minio/health/live"
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 60s
        volumes:
            - ./docker-data/minio:/data:z

# The Docker networks.
networks:
    local:
        driver: "bridge"
        name: ${NETWORK_NAME:-local_dbs_network}

# The Docker volumes.
volumes:
    db_data:
        driver: "local"
        name: "${DB_CONTAINER_NAME:-db}_data"
