version: "3.9"

services:
    pgsql:
        image: postgres:latest
        container_name: "${PGSQL_CONTAINER_NAME:-pgsql}"
        environment:
            POSTGRES_USER: "${PGSQL_USERNAME}"
            POSTGRES_PASSWORD: "${PGSQL_PASSWORD}"
            POSTGRES_DB: "${PGSQL_DATABASE}"
        healthcheck:
            test: ["CMD", "pg_isready", "-q", "-d", "${PGSQL_DATABASE}", "-U", "${PGSQL_USERNAME}"]
            retries: 3
            timeout: 5s
        networks:
            - local
        # Map the database container exposed port to the host port.
        ports:
            - ${PGSQL_PORT:-5432}:5432
        volumes:
            - pgsql_data:/var/lib/postgresql/data
    minio:
        image: quay.io/minio/minio:RELEASE.2023-05-18T00-05-36Z
        command: server /data --console-address ":9001"
        restart: unless-stopped
        ports:
            - 9001:9001
            - 9000:9000
        environment:
            MINIO_ROOT_USER: minio
            MINIO_ROOT_PASSWORD: asdfasdf
        healthcheck:
            test: "curl -f http://localhost:9000/minio/health/live"
            interval: 30s
            timeout: 10s
            retries: 5
            start_period: 60s
        volumes:
            - ./docker-data/minio:/data:z

# The Docker networks.
networks:
    local:
        driver: "bridge"
        name: ${NETWORK_NAME:-local_dbs_network}

# The Docker volumes.
volumes:
    pgsql_data:
        driver: "local"
        name: "${PGSQL_CONTAINER_NAME:-pgsql}_data"
